"use client";

import Image from "next/image";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, BadgeCheck, CalendarClock, Check, CheckCircle2, ClipboardCheck, FileCheck2, FileImage, ListChecks, Loader2, MapPin, Pencil, Plus, RefreshCw, ScanSearch, Send, ShieldCheck, UserRoundCheck, WalletCards } from "lucide-react";
import { PageHeading } from "@/components/app-shell";
import { claimApi, describeApiError, isMissingEndpoint } from "@/lib/api";
import type { ClaimDossier, ClaimSubmission, ClaimTask, LineItem, Role, TeamMember, WorkflowStatus } from "@/lib/types";
import { DEMO_ACTOR_BY_ROLE, auditForClaim, claimAddress, claimInsuredName, claimPayment, itemsForClaim, membersFromResponse, notesForClaim, tasksForClaim } from "@/lib/types";

const USD = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", minimumFractionDigits: 2, maximumFractionDigits: 2 });
const EMPTY_FORM: ClaimSubmission = { insured_name: "Jordan & Casey Morgan", policy_number: "APH-48392071", incident_date: "2026-09-12", peril: "WATER", loss_address: "1847 Hawthorne Avenue, Dallas, TX", zip_code: "75201", deductible: 1000, material_age: "4", material_age_years: 4, incident_brief: "Supply line beneath the kitchen sink failed overnight. Water pooled across the hardwood and migrated under base cabinets. Emergency mitigation began this morning; no prior water loss at this location.", evidence: [{ filename: "/kitchen-water-damage.jpg", media_type: "IMAGE", label: "Kitchen damage photograph" }] };

type EditableItem = { id: string; category: string; description: string; quantity: number; unit: string; unitPrice: number; depreciation: number };
function editableItems(claim: ClaimDossier | null): EditableItem[] { return itemsForClaim(claim || { claim_id: "", status: "SUBMITTED" }).map((item, index) => ({ id: item.id || item.zone_id || `LINE_${index + 1}`, category: item.category || item.trade || "Repair", description: item.description || "Reviewed repair item", quantity: Number(item.quantity || 0), unit: item.unit || "EA", unitPrice: Number(item.unit_price ?? item.unitPrice ?? 0), depreciation: Number(item.depreciation_percent ?? (item.rcv ? Number(item.depreciation || 0) / Number(item.rcv) * 100 : 0)) })); }

export function ClaimWorkspace({ claimId, role, onBack }: { claimId: string | null; role: Role; onBack: () => void }) {
  const [claim, setClaim] = useState<ClaimDossier | null>(null);
  const [form, setForm] = useState<ClaimSubmission>(EMPTY_FORM);
  const [items, setItems] = useState<EditableItem[]>([]);
  const [team, setTeam] = useState<TeamMember[]>([]);
  const [loading, setLoading] = useState(Boolean(claimId));
  const [submitting, setSubmitting] = useState(false);
  const [analysisLoading, setAnalysisLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [reviewNote, setReviewNote] = useState("Evidence and estimate reviewed. Release settlement once payment preference is confirmed.");
  const [newTask, setNewTask] = useState("");
  const [newNote, setNewNote] = useState("");
  const actorId = DEMO_ACTOR_BY_ROLE[role];
  const adopt = (next: ClaimDossier) => { setClaim(next); setItems(editableItems(next)); setForm((old) => ({ ...old, insured_name: next.submission?.homeowner_name || next.submission?.insured_name || old.insured_name, policy_number: next.submission?.policy_number || old.policy_number, incident_date: next.submission?.incident_date || old.incident_date, peril: next.submission?.peril || old.peril, loss_address: claimAddress(next), zip_code: next.submission?.zip_code || old.zip_code, deductible: next.submission?.deductible ?? old.deductible, material_age: String(next.submission?.material_age_years ?? old.material_age), material_age_years: next.submission?.material_age_years ?? old.material_age_years, incident_brief: next.submission?.incident_description || old.incident_brief })); };
  const load = useCallback(async () => { if (!claimId) { setLoading(false); return; } setLoading(true); setError(null); try { adopt(await claimApi.get(claimId)); } catch (caught) { setError(describeApiError(caught)); } finally { setLoading(false); } }, [claimId]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { claimApi.team().then((response) => setTeam(membersFromResponse(response))).catch(() => setTeam([])); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSubmitting(true); setError(null); setNotice(null); try { const created = await claimApi.submit(form); adopt(created); setNotice(`Claim ${created.claim_id} was submitted. Run deterministic analysis when ready.`); } catch (caught) { setError(describeApiError(caught)); } finally { setSubmitting(false); } };
  const analyze = async () => { if (!claim) return; setAnalysisLoading(true); setError(null); try { const next = await claimApi.analyze(claim.claim_id); adopt(next); setNotice("Analysis completed. The deterministic estimate is ready for desk review."); } catch (caught) { setError(describeApiError(caught)); } finally { setAnalysisLoading(false); } };
  const approve = async () => { if (!claim) return; setActionLoading("approve"); setError(null); try { const next = await claimApi.approve(claim.claim_id, { decision: "APPROVE", line_items: items.map((item) => ({ id: item.id, quantity: item.quantity, unit_price: item.unitPrice })), reviewer_notes: reviewNote, adjuster_name: role === "SUPERVISOR" ? "Demo Supervisor" : "Demo Desk Adjuster" }); adopt(next); setNotice(`Claim ${next.claim_id} approved through the VOW proof boundary.`); } catch (caught) { setError(describeApiError(caught)); } finally { setActionLoading(null); } };
  const invoke = async (key: string, request: () => Promise<ClaimDossier>, success: string) => { setActionLoading(key); setError(null); try { adopt(await request()); setNotice(success); } catch (caught) { setError(describeApiError(caught)); } finally { setActionLoading(null); } };
  const totals = useMemo(() => { const rcv = items.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0); const depreciation = items.reduce((sum, item) => sum + item.quantity * item.unitPrice * item.depreciation / 100, 0); const acv = rcv - depreciation; const deductible = claim?.estimate?.deductible ?? form.deductible; return { rcv, depreciation, acv, deductible, net: Math.max(0, acv - deductible) }; }, [claim?.estimate?.deductible, form.deductible, items]);
  const updateItem = (id: string, field: "quantity" | "unitPrice", value: string) => setItems((current) => current.map((item) => item.id === id ? { ...item, [field]: Math.max(0, Number(value) || 0) } : item));
  const addTask = async (event: FormEvent) => { event.preventDefault(); if (!claim || !newTask.trim()) return; const ownerId = claim.assignments?.field_adjuster_id || actorId; await invoke("task", () => claimApi.createTask(claim.claim_id, { title: newTask.trim(), owner_id: ownerId, priority: "NORMAL" }), "Task added to the claim."); setNewTask(""); };
  const addNote = async (event: FormEvent) => { event.preventDefault(); if (!claim || !newNote.trim()) return; await invoke("note", () => claimApi.addNote(claim.claim_id, { author_id: actorId, body: newNote.trim(), visibility: "INTERNAL" }), "Internal note added to the audit record."); setNewNote(""); };
  if (!claimId && !claim) return <NewClaimForm form={form} setForm={setForm} submitting={submitting} onSubmit={submit} onBack={onBack} />;
  if (loading && !claim) return <div className="page-frame"><button onClick={onBack} className="back-button"><ArrowLeft className="h-4 w-4" />Back to queue</button><div className="card mt-4 space-y-5 p-6">{[1,2,3,4].map((line) => <span key={line} className="skeleton-line block w-full" />)}</div></div>;
  if (!claim) return <div className="page-frame"><button onClick={onBack} className="back-button"><ArrowLeft className="h-4 w-4" />Back to queue</button><div role="alert" className="state-error mt-4"><AlertTriangle className="h-5 w-5" /><div><strong>Claim workspace unavailable.</strong><p>{error || "No claim was returned."}</p></div><button className="secondary-button" onClick={() => void load()}>Retry</button></div></div>;
  const analyzed = Boolean(claim.estimate && claim.vision_data);
  const approved = claim.status === "APPROVED" || Boolean(claim.assurance);
  const payment = claimPayment(claim);
  return <div className="page-frame">
    <button onClick={onBack} className="back-button"><ArrowLeft className="h-4 w-4" />Back to queue</button>
    <PageHeading eyebrow="Claim workspace" title={claimInsuredName(claim)} description={`${claim.claim_id} · ${claim.submission?.peril || "Property loss"} · ${claimAddress(claim)}`} action={<div className="flex items-center gap-2"><span className="status-badge">{claim.status.replaceAll("_", " ")}</span><button type="button" className="secondary-button" onClick={() => void load()}><RefreshCw className="h-4 w-4" />Refresh</button></div>} />
    {error && <div role="alert" className="state-error"><AlertTriangle className="h-5 w-5" /><div><strong>Action could not be completed.</strong><p>{error}</p></div><button className="secondary-button" onClick={() => setError(null)}>Dismiss</button></div>}
    {notice && !error && <div role="status" className="state-success"><CheckCircle2 className="h-5 w-5" /><span>{notice}</span></div>}
    <Lifecycle status={claim.status} />
    <div className="grid gap-6 2xl:grid-cols-[minmax(0,1.4fr)_390px]">
      <div className="space-y-6">
        <section className="card"><div className="section-heading"><div><p>Evidence and vision</p><h2>Kitchen Water Damage dossier</h2></div><FileImage className="h-5 w-5 text-cyan" /></div><div className="grid gap-5 p-5 lg:grid-cols-[1.12fr_.88fr]"><EvidenceOverlay /><div className="space-y-3"><div className="border-l-4 border-safety bg-orange-50 p-3"><p className="text-xs font-bold uppercase tracking-wider text-safety">Primary loss driver</p><p className="mt-1 font-bold">Supply-line discharge below sink</p><p className="mt-1 text-sm leading-5 text-slate-600">Visible water exposure beneath base cabinets and across finished flooring.</p></div><Telemetry label="Capture integrity" value={claim.telemetry?.exif_tamper_flag === false ? "EXIF verified" : "Unknown"} /><Telemetry label="Evidence count" value={claim.evidence ? `${claim.evidence.length} file${claim.evidence.length === 1 ? "" : "s"}` : "Unknown"} /><Telemetry label="Analysis status" value={analyzed ? "Deterministic scope available" : "Awaiting analysis"} /></div></div>{!analyzed && <div className="border-t border-slate-200 p-5"><button type="button" className="primary-button" disabled={analysisLoading} onClick={() => void analyze()}>{analysisLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <ScanSearch className="h-4 w-4" />}{analysisLoading ? "Analyzing" : "Run deterministic analysis"}</button><p className="mt-2 text-xs text-slate-500">Analysis runs the existing server-authoritative pricing workflow; AEGIS does not simulate a claim decision.</p></div>}</section>
        {analyzed && <section className="card overflow-hidden"><div className="section-heading"><div><p>Repair estimate</p><h2>Exact deterministic line-item review</h2></div><WalletCards className="h-5 w-5 text-cyan" /></div><div className="overflow-x-auto"><table className="estimate-table"><thead><tr><th>Trade / description</th><th>Qty</th><th>Unit</th><th>Unit price</th><th>RCV</th><th>Dep.</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><small>{item.category}</small><strong>{item.description}</strong></td><td><input aria-label={`${item.description} quantity`} type="number" className="table-input" min="0" step="0.01" value={item.quantity} onChange={(event) => updateItem(item.id, "quantity", event.target.value)} /></td><td>{item.unit}</td><td><input aria-label={`${item.description} unit price`} type="number" className="table-input" min="0" step="0.01" value={item.unitPrice} onChange={(event) => updateItem(item.id, "unitPrice", event.target.value)} /></td><td className="text-right font-bold">{USD.format(item.quantity * item.unitPrice)}</td><td className="text-right">{item.depreciation.toFixed(1)}%</td></tr>)}</tbody></table></div></section>}
        <Collaboration claim={claim} actorId={actorId} newTask={newTask} setNewTask={setNewTask} newNote={newNote} setNewNote={setNewNote} addTask={addTask} addNote={addNote} actionLoading={actionLoading} invoke={invoke} />
      </div>
      <aside className="space-y-6"><section className="card"><div className="section-heading"><div><p>Claim controls</p><h2>Assignment and lifecycle</h2></div><UserRoundCheck className="h-5 w-5 text-cyan" /></div><div className="space-y-4 p-5"><label className="field-label" htmlFor="field-owner">Field adjuster</label><select id="field-owner" className="field" value={claim.assignments?.field_adjuster_id || ""} onChange={(event) => void invoke("assign-field", () => claimApi.assign(claim.claim_id, { field_adjuster_id: event.target.value || null, desk_adjuster_id: claim.assignments?.desk_adjuster_id || null }), "Field assignment updated.")} disabled={actionLoading === "assign-field"}><option value="">Unassigned</option>{team.map((member) => <option key={member.user_id} value={member.user_id}>{member.name} — {String(member.role).replaceAll("_", " ")}</option>)}</select><label className="field-label" htmlFor="desk-owner">Desk adjuster</label><select id="desk-owner" className="field" value={claim.assignments?.desk_adjuster_id || ""} onChange={(event) => void invoke("assign-desk", () => claimApi.assign(claim.claim_id, { desk_adjuster_id: event.target.value || null, field_adjuster_id: claim.assignments?.field_adjuster_id || null }), "Desk assignment updated.")} disabled={actionLoading === "assign-desk"}><option value="">Unassigned</option>{team.map((member) => <option key={member.user_id} value={member.user_id}>{member.name} — {String(member.role).replaceAll("_", " ")}</option>)}</select><div className="border-t border-slate-200 pt-4"><p className="field-label">Controlled status</p><div className="flex flex-wrap gap-2">{(claim.status === "SUBMITTED" ? ["IN_REVIEW"] : claim.status === "PAID" ? ["CLOSED"] : []).map((next) => <button type="button" key={next} className="secondary-button" disabled={Boolean(actionLoading)} onClick={() => void invoke(`status-${next}`, () => claimApi.setStatus(claim.claim_id, next as WorkflowStatus, actorId), `Claim moved to ${next.replaceAll("_", " ")}.`)}>{next === "CLOSED" ? "Close claim" : "Move to review"}</button>)}</div><p className="mt-2 text-xs leading-5 text-slate-500">Lifecycle changes are sent to the API and permitted only by its controlled transition table.</p></div></div></section>
        <SettlementCard totals={totals} analyzed={analyzed} approved={approved} reviewNote={reviewNote} setReviewNote={setReviewNote} actionLoading={actionLoading} onApprove={approve} assurance={claim.assurance} claimId={claim.claim_id} />
        <PaymentCard claim={claim} payment={payment} actorId={actorId} actionLoading={actionLoading} invoke={invoke} />
        <Timeline claim={claim} />
      </aside>
    </div>
  </div>;
}

function NewClaimForm({ form, setForm, submitting, onSubmit, onBack }: { form: ClaimSubmission; setForm: React.Dispatch<React.SetStateAction<ClaimSubmission>>; submitting: boolean; onSubmit: (event: FormEvent) => void; onBack: () => void }) { const set = <K extends keyof ClaimSubmission>(key: K, value: ClaimSubmission[K]) => setForm((current) => ({ ...current, [key]: value })); return <div className="page-frame"><button onClick={onBack} className="back-button"><ArrowLeft className="h-4 w-4" />Back to queue</button><PageHeading eyebrow="New property loss" title="Kitchen Water Damage intake" description="Capture known facts once, then submit the existing server-authoritative claim lifecycle." /><form onSubmit={onSubmit} className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="card"><div className="section-heading"><div><p>Evidence</p><h2>Loss documentation</h2></div><FileImage className="h-5 w-5 text-cyan" /></div><div className="grid gap-5 p-5 sm:grid-cols-[230px_1fr]"><div className="relative aspect-[4/3] overflow-hidden border border-slate-200"><Image src="/kitchen-water-damage.jpg" alt="Kitchen water damage evidence" fill className="object-cover" sizes="230px" /><span className="absolute bottom-2 left-2 bg-ink px-2 py-1 text-[10px] font-bold text-white">PRIMARY EVIDENCE</span></div><div><p className="font-bold">kitchen-water-damage.jpg</p><p className="mt-1 text-sm text-slate-500">Attached as the Kitchen Water Damage demonstration evidence.</p><label className="field-label mt-5" htmlFor="brief">Incident brief</label><textarea id="brief" required className="field min-h-36 resize-y" value={form.incident_brief} onChange={(event) => set("incident_brief", event.target.value)} /></div></div></section><aside className="card p-5"><div className="grid gap-4"><Input label="Named insured" value={form.insured_name} onChange={(value) => set("insured_name", value)} /><Input label="Policy number" value={form.policy_number} onChange={(value) => set("policy_number", value)} /><Input label="Loss address" value={form.loss_address} onChange={(value) => set("loss_address", value)} /><div className="grid grid-cols-2 gap-4"><Input label="ZIP code" value={form.zip_code} onChange={(value) => set("zip_code", value)} /><Input label="Deductible" type="number" value={String(form.deductible)} onChange={(value) => set("deductible", Number(value) || 0)} /></div><Input label="Date of loss" type="date" value={form.incident_date} onChange={(value) => set("incident_date", value)} /><button className="primary-button mt-2" disabled={submitting}>{submitting ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{submitting ? "Submitting" : "Submit claim"}</button></div></aside></form></div>; }
function Input({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { const id = label.toLowerCase().replaceAll(" ", "-"); return <label><span className="field-label">{label}</span><input id={id} required type={type} className="field" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function EvidenceOverlay() { return <div className="relative aspect-video overflow-hidden border border-slate-200 bg-slate-100"><Image src="/kitchen-water-damage.jpg" alt="Kitchen damage evidence with localized flooring, baseboard, drywall, and air mover overlays" fill className="object-cover" sizes="(max-width: 1024px) 100vw, 650px" priority /><div className="absolute bottom-[8%] left-[4%] h-[29%] w-[68%] border-2 border-cyan bg-cyan/10"><span className="overlay-tag bg-cyan text-ink">Flooring · 0.91</span></div><div className="absolute bottom-[30%] left-[32%] h-[12%] w-[47%] border-2 border-safety bg-orange-400/10"><span className="overlay-tag bg-safety text-white">Baseboard · 0.96</span></div><div className="absolute bottom-[41%] right-[17%] h-[23%] w-[18%] border-2 border-violet-600 bg-violet-400/10"><span className="overlay-tag right-0 bg-violet-700 text-white">Drywall · 0.94</span></div><div className="absolute bottom-3 left-3 bg-ink/95 px-3 py-2 text-xs text-white"><strong className="text-cyan">4 zones</strong> localized · 0.95 mean confidence</div></div>; }
function Telemetry({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between border-b border-slate-100 py-2 text-sm"><span className="text-slate-500">{label}</span><strong className="text-right">{value}</strong></div>; }
function Lifecycle({ status }: { status: string }) { const stages = ["SUBMITTED", "IN_REVIEW", "APPROVED", "PAYMENT_SCHEDULED", "PAID", "CLOSED"]; const active = Math.max(0, stages.indexOf(status)); return <ol className="mb-6 flex overflow-x-auto border-y border-slate-200 bg-white">{stages.map((stage, index) => <li key={stage} className={`flex min-w-[140px] items-center gap-2 border-r border-slate-100 px-3 py-3 text-xs font-bold ${index <= active ? "text-ink" : "text-slate-400"}`}><span className={`grid h-5 w-5 place-items-center rounded-full ${index < active ? "bg-cyan text-ink" : index === active ? "bg-ink text-cyan" : "bg-slate-100"}`}>{index < active ? <Check className="h-3 w-3" /> : index + 1}</span>{stage.replaceAll("_", " ")}</li>)}</ol>; }
function SettlementCard({ totals, analyzed, approved, reviewNote, setReviewNote, actionLoading, onApprove, assurance, claimId }: { totals: { rcv: number; depreciation: number; acv: number; deductible: number; net: number }; analyzed: boolean; approved: boolean; reviewNote: string; setReviewNote: (value: string) => void; actionLoading: string | null; onApprove: () => void; assurance: ClaimDossier["assurance"]; claimId: string }) { return <section className="border border-ink bg-ink text-white"><div className="border-b border-slate-700 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan">VOW authorization</p><h2 className="mt-1 font-bold">Proof-gated settlement</h2></div><div className="space-y-3 p-5 text-sm"><Price label="Replacement cost" value={USD.format(totals.rcv)} /><Price label="Less depreciation" value={`−${USD.format(totals.depreciation)}`} /><Price label="Actual cash value" value={USD.format(totals.acv)} /><Price label="Less deductible" value={`−${USD.format(totals.deductible)}`} /><div className="flex items-end justify-between border-t border-slate-700 pt-4"><strong>Net payout</strong><strong className="text-2xl text-cyan">{USD.format(totals.net)}</strong></div>{!approved && <><label className="sr-only" htmlFor="review-note">Review note</label><textarea id="review-note" className="field min-h-24 resize-y text-ink" value={reviewNote} onChange={(event) => setReviewNote(event.target.value)} /><button type="button" className="w-full bg-safety px-4 py-3 font-bold text-white hover:bg-[#d85727] disabled:cursor-not-allowed disabled:opacity-60" disabled={!analyzed || actionLoading === "approve"} onClick={onApprove}>{actionLoading === "approve" ? <span className="flex items-center justify-center gap-2"><Loader2 className="h-4 w-4 animate-spin" />Running VOW proof gate</span> : "Authorize & approve"}</button><p className="text-xs leading-5 text-slate-300">Authorization is server-calculated and crosses the immutable VOW effect boundary.</p></>}{assurance && <div className="border border-teal-300 bg-teal-50 p-3 text-xs text-teal-950"><p className="flex items-center gap-2 font-bold"><ShieldCheck className="h-4 w-4" />VOW assurance verified</p><p className="mt-2 break-all">Run: {assurance.run_id || "Unknown"}</p><div className="mt-3 flex flex-wrap gap-2"><a className="evidence-link" href={claimApi.evidenceUrl(claimId)}>Download signed evidence</a><a className="evidence-link" href={`${claimApi.evidenceUrl(claimId)}/../verify`} target="_blank" rel="noreferrer">Verify receipt</a></div></div>}</div></section>; }
function Price({ label, value }: { label: string; value: string }) { return <div className="flex justify-between text-slate-300"><span>{label}</span><span>{value}</span></div>; }
function Collaboration(props: {
  claim: ClaimDossier;
  actorId: string;
  newTask: string;
  setNewTask: (value: string) => void;
  newNote: string;
  setNewNote: (value: string) => void;
  addTask: (event: FormEvent) => void;
  addNote: (event: FormEvent) => void;
  actionLoading: string | null;
  invoke: (key: string, request: () => Promise<ClaimDossier>, success: string) => void;
}) {
  const { claim, actorId, newTask, setNewTask, newNote, setNewNote, addTask, addNote, actionLoading, invoke } = props;
  const tasks = tasksForClaim(claim);
  const notes = notesForClaim(claim);
  return <section className="grid gap-6 lg:grid-cols-2">
    <section className="card">
      <div className="section-heading"><div><p>Work coordination</p><h2>Tasks</h2></div><ListChecks className="h-5 w-5 text-cyan" /></div>
      <div className="divide-y divide-slate-100">
        {tasks.length ? tasks.map((task: ClaimTask, index) => {
          const taskId = task.task_id || task.id || String(index);
          const complete = task.status === "COMPLETE" || Boolean(task.completed_at);
          return <div key={taskId} className="flex items-center gap-3 p-4">
            <span className={`grid h-6 w-6 place-items-center border ${complete ? "border-teal-500 bg-teal-50 text-teal-700" : "border-slate-300"}`}>{complete && <Check className="h-4 w-4" />}</span>
            <div className="min-w-0 flex-1"><p className="text-sm font-bold">{task.title}</p><p className="text-xs text-slate-500">{task.owner_name || task.owner_id || "Owner unknown"} · {task.priority || "NORMAL"}</p></div>
            {!complete && <button type="button" className="row-action" disabled={actionLoading === `complete-${taskId}`} onClick={() => void invoke(`complete-${taskId}`, () => claimApi.completeTask(claim.claim_id, taskId, actorId), "Task completed and added to the audit history.")}>{actionLoading === `complete-${taskId}` ? "Saving" : "Complete"}</button>}
          </div>;
        }) : <p className="p-4 text-sm text-slate-500">No tasks returned for this claim.</p>}
      </div>
      <form className="flex gap-2 border-t border-slate-200 p-4" onSubmit={addTask}>
        <label className="sr-only" htmlFor="new-task">New task</label><input id="new-task" value={newTask} onChange={(event) => setNewTask(event.target.value)} className="field" placeholder="Add a claim task" />
        <button className="secondary-button shrink-0" disabled={!newTask.trim() || actionLoading === "task"}><Plus className="h-4 w-4" />Add</button>
      </form>
    </section>
    <section className="card">
      <div className="section-heading"><div><p>Role-aware record</p><h2>Internal notes</h2></div><Pencil className="h-5 w-5 text-cyan" /></div>
      <div className="max-h-72 divide-y divide-slate-100 overflow-y-auto">{notes.length ? notes.map((note, index) => <div key={note.note_id || note.id || index} className="p-4"><p className="text-sm leading-6">{note.body}</p><p className="mt-2 text-xs text-slate-500">{note.author_name || note.author_id || "Author unknown"}{note.created_at ? ` · ${new Date(note.created_at).toLocaleString()}` : ""}</p></div>) : <p className="p-4 text-sm text-slate-500">No internal notes returned for this claim.</p>}</div>
      <form className="border-t border-slate-200 p-4" onSubmit={addNote}>
        <label className="sr-only" htmlFor="new-note">Internal note</label><textarea id="new-note" value={newNote} onChange={(event) => setNewNote(event.target.value)} className="field min-h-20 resize-y" placeholder="Record a role-aware internal note" />
        <button className="secondary-button mt-2" disabled={!newNote.trim() || actionLoading === "note"}><Pencil className="h-4 w-4" />Add note</button>
      </form>
    </section>
  </section>;
}

function PaymentCard({ claim, payment, actorId, actionLoading, invoke }: { claim: ClaimDossier; payment: ReturnType<typeof claimPayment>; actorId: string; actionLoading: string | null; invoke: (key: string, request: () => Promise<ClaimDossier>, success: string) => Promise<void> }) { const permitted = claim.status === "APPROVED" || claim.status === "PAYMENT_SCHEDULED" || claim.status === "PAID"; return <section className="card"><div className="section-heading"><div><p>Finance control</p><h2>Mock payment instruction</h2></div><CalendarClock className="h-5 w-5 text-cyan" /></div><div className="p-5"><p className="text-sm leading-6 text-slate-600">AEGIS records a mock instruction only. It never transfers funds.</p><dl className="mt-4 space-y-2 text-sm"><Telemetry label="Status" value={payment?.status || "Not scheduled"} /><Telemetry label="Method" value={payment?.method || "Unknown"} /><Telemetry label="Amount" value={typeof payment?.amount === "number" ? USD.format(payment.amount) : "Unknown"} /></dl>{!payment?.status && <button type="button" className="primary-button mt-4" disabled={!permitted || Boolean(actionLoading)} onClick={() => void invoke("schedule-payment", () => claimApi.payment(claim.claim_id, { action: "SCHEDULE", method: "ACH", actor_id: actorId }), "Mock ACH payment scheduled.")}><WalletCards className="h-4 w-4" />Schedule mock ACH</button>}{payment?.status === "SCHEDULED" && <button type="button" className="secondary-button mt-4" disabled={Boolean(actionLoading)} onClick={() => void invoke("send-payment", () => claimApi.payment(claim.claim_id, { action: "MARK_SENT", actor_id: actorId }), "Mock payment marked sent.")}><Send className="h-4 w-4" />Mark instruction sent</button>}{!permitted && <p className="mt-3 text-xs text-safety">Approval is required before a payment instruction can be scheduled.</p>}</div></section>; }
function Timeline({ claim }: { claim: ClaimDossier }) { const audit = auditForClaim(claim); return <section className="card"><div className="section-heading"><div><p>Immutable record</p><h2>Lifecycle timeline</h2></div><ClipboardCheck className="h-5 w-5 text-cyan" /></div><ol className="divide-y divide-slate-100">{audit.length ? audit.slice().reverse().map((event, index) => <li key={`${event.event}-${index}`} className="relative p-4 pl-9"><span className="absolute left-4 top-5 h-2.5 w-2.5 rounded-full bg-cyan" /><p className="text-sm font-bold">{event.event.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-slate-500">{event.actor || "System"}{event.occurred_at ? ` · ${new Date(event.occurred_at).toLocaleString()}` : ""}</p></li>) : <li className="p-4 text-sm text-slate-500">No audit events were returned.</li>}</ol></section>; }
