import { useCallback } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { api } from '@/lib/api';
import type { Claim } from '@/lib/types';
import { claimId } from '@/lib/types';
import { AppIcon, ScreenContainer } from '@/components/brand-and-shell';
import { ClaimCard } from '@/components/ui';
export default function ClaimsScreen() { const claimsQuery = useQuery({ queryKey: ['claims'], queryFn: api.claims }); const claims = claimsQuery.data ?? []; const refresh = useCallback(async () => { await claimsQuery.refetch(); }, [claimsQuery]); const openClaim = useCallback((claim: Claim) => { const id = claimId(claim); if (id !== 'Unknown claim') router.push({ pathname: '/claim/[id]', params: { id } }); }, []); return <ScreenContainer title="Claims" subtitle="Assigned and demo claim queue">{claimsQuery.isLoading ? <View style={styles.center}><ActivityIndicator color="#18C3CC" size="large" /><Text style={styles.loadingText}>Loading claims…</Text></View> : null}{claimsQuery.error ? <View style={styles.center}><AppIcon icon="warning" color="#9A3412" size={26} /><Text style={styles.errorTitle}>Claims could not be loaded</Text><Text style={styles.errorCopy}>{claimsQuery.error.message}</Text><Text style={styles.errorCopy}>Pull down to retry when the API is reachable.</Text></View> : null}{!claimsQuery.isLoading && !claimsQuery.error ? <FlatList data={claims} keyExtractor={(item, index) => `${claimId(item)}-${index}`} renderItem={({ item }) => <ClaimCard claim={item} onPress={() => openClaim(item)} />} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={claimsQuery.isRefetching} onRefresh={refresh} tintColor="#18C3CC" />} ListHeaderComponent={<Text style={styles.summary}>{claims.length} claim{claims.length === 1 ? '' : 's'} available</Text>} ListEmptyComponent={<View style={styles.empty}><AppIcon icon="claims" size={28} color="#526273" /><Text style={styles.emptyTitle}>No claims in this queue</Text><Text style={styles.emptyCopy}>Use Demo reset in Settings to create the Kitchen Water Damage claim.</Text></View>} /> : null}</ScreenContainer>; }
const styles = StyleSheet.create({ center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 28 }, loadingText: { color: '#526273', marginTop: 12 }, errorTitle: { color: '#10233D', fontSize: 18, fontWeight: '800', marginTop: 12 }, errorCopy: { color: '#7C2D12', fontSize: 14, lineHeight: 20, textAlign: 'center', marginTop: 7 }, list: { padding: 18, paddingBottom: 30 }, summary: { color: '#526273', fontSize: 13, marginBottom: 12 }, empty: { padding: 28, borderRadius: 14, borderWidth: 1, borderColor: '#DCE3E8', borderStyle: 'dashed', alignItems: 'center', backgroundColor: '#FFFFFF' }, emptyTitle: { color: '#10233D', fontSize: 16, fontWeight: '800', marginTop: 10 }, emptyCopy: { color: '#526273', textAlign: 'center', lineHeight: 20, marginTop: 5 } });
