import { useCallback } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { api, apiBaseUrl } from '@/lib/api';
import { asArray, asRecord, nestedValue, text } from '@/lib/types';
import { useRole } from '@/context/role-context';
import { AppIcon, ScreenContainer } from '@/components/brand-and-shell';
import { MetricCard } from '@/components/ui';
function ErrorPanel({ message }: { message: string }) { return <View style={styles.errorPanel}><AppIcon icon="warning" size={20} color="#9A3412" /><Text style={styles.errorText}>{message}</Text></View>; }
export default function HomeScreen() {
  const { role } = useRole(); const health = useQuery({ queryKey: ['health'], queryFn: api.health }); const dashboard = useQuery({ queryKey: ['dashboard'], queryFn: api.dashboard });
  const refresh = useCallback(async () => { await Promise.all([health.refetch(), dashboard.refetch()]); }, [health, dashboard]);
  const metrics = asRecord(dashboard.data?.metrics); const workload = asArray<Record<string, unknown>>(dashboard.data?.team_workload); const recent = asArray<Record<string, unknown>>(dashboard.data?.recent_activity);
  const nextInspection = dashboard.data?.next_inspection ?? metrics.next_inspection ?? recent[0]?.created_at ?? recent[0]?.timestamp;
  return <ScreenContainer title="Command center" subtitle={role === 'FIELD_ADJUSTER' ? 'Field adjuster workspace' : 'Policyholder view'}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={health.isRefetching || dashboard.isRefetching} onRefresh={refresh} tintColor="#18C3CC" />}>
    <View style={styles.roleBand}><AppIcon icon="person" color="#18C3CC" size={20} /><View><Text style={styles.roleLabel}>DEMO ROLE</Text><Text style={styles.roleValue}>{role === 'FIELD_ADJUSTER' ? 'Field Adjuster' : 'Policyholder'}</Text></View></View>
    <View style={styles.healthRow}><AppIcon icon={health.data?.status === 'ok' ? 'verified' : 'wifiOff'} color={health.data?.status === 'ok' ? '#147D3F' : '#9A3412'} size={19} /><Text style={styles.healthText}>{health.isLoading ? 'Checking API health…' : health.data?.status === 'ok' ? 'API health verified' : 'API health unavailable'}</Text></View>
    {health.error ? <ErrorPanel message={`Health check failed: ${health.error.message}. Confirm EXPO_PUBLIC_API_URL is reachable from this device.`} /> : null}{dashboard.error ? <ErrorPanel message={`Dashboard failed: ${dashboard.error.message}. Pull to refresh after the API is available.`} /> : null}
    <Text style={styles.sectionTitle}>Today’s workload</Text>{dashboard.isLoading ? <ActivityIndicator color="#18C3CC" size="large" style={styles.loader} /> : <View style={styles.metrics}><MetricCard label="Open claims" value={text(metrics.open_claims ?? metrics.open ?? metrics.claims_open, '—')} /><MetricCard label="Queue aging" value={text(metrics.queue_aging ?? metrics.average_queue_age ?? metrics.in_review, '—')} /><MetricCard label="Evidence ready" value={text(metrics.evidence_ready_rate ?? metrics.evidence_readiness, '—')} /></View>}
    <View style={styles.inspectionCard}><View style={styles.inspectionIcon}><AppIcon icon="clock" color="#18C3CC" size={22} /></View><View style={styles.inspectionCopy}><Text style={styles.cardEyebrow}>NEXT INSPECTION</Text><Text style={styles.inspectionTitle}>{typeof nextInspection === 'string' ? nextInspection : nestedValue(asRecord(nextInspection), ['label', 'scheduled_at', 'due_at'], 'No inspection scheduled')}</Text><Text style={styles.inspectionHelp}>Live workload and inspection timing are supplied by /api/dashboard.</Text></View></View>
    <Text style={styles.sectionTitle}>Team workload</Text>{workload.length ? workload.map((person, index) => <View style={styles.workloadRow} key={`${text(person.user_id ?? person.name, 'member')}-${index}`}><Text style={styles.workloadName}>{text(person.name ?? person.user_name ?? person.user_id, 'Team member')}</Text><Text style={styles.workloadCount}>{text(person.open_claims ?? person.count ?? person.assigned_claims, '0')} open</Text></View>) : <Text style={styles.empty}>No team workload is available yet.</Text>}<Text style={styles.apiNote}>API: {apiBaseUrl}</Text>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 30 }, roleBand: { backgroundColor: '#10233D', borderRadius: 14, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 11 }, roleLabel: { color: '#BEEEF1', fontSize: 10, fontWeight: '800', letterSpacing: 1 }, roleValue: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', marginTop: 3 }, healthRow: { flexDirection: 'row', gap: 7, alignItems: 'center', marginTop: 15 }, healthText: { color: '#314252', fontSize: 13, fontWeight: '700' }, errorPanel: { marginTop: 13, backgroundColor: '#FFF0E5', borderColor: '#FDBA74', borderWidth: 1, borderRadius: 10, padding: 12, flexDirection: 'row', gap: 8 }, errorText: { color: '#7C2D12', fontSize: 13, lineHeight: 19, flex: 1 }, sectionTitle: { color: '#10233D', fontSize: 18, fontWeight: '800', marginTop: 23, marginBottom: 11 }, loader: { marginVertical: 25 }, metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, inspectionCard: { marginTop: 16, backgroundColor: '#FFFFFF', borderColor: '#DCE3E8', borderWidth: 1, borderRadius: 14, padding: 15, flexDirection: 'row', gap: 12 }, inspectionIcon: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#E8F8F9', justifyContent: 'center', alignItems: 'center' }, inspectionCopy: { flex: 1 }, cardEyebrow: { color: '#0B7178', fontWeight: '800', letterSpacing: 0.8, fontSize: 10 }, inspectionTitle: { color: '#10233D', fontSize: 15, lineHeight: 21, fontWeight: '800', marginTop: 4 }, inspectionHelp: { color: '#526273', fontSize: 12, lineHeight: 18, marginTop: 4 }, workloadRow: { backgroundColor: '#FFFFFF', borderBottomColor: '#E5EAEE', borderBottomWidth: 1, paddingHorizontal: 14, paddingVertical: 14, flexDirection: 'row', justifyContent: 'space-between' }, workloadName: { color: '#10233D', fontWeight: '700', flex: 1 }, workloadCount: { color: '#0B7178', fontWeight: '800' }, empty: { color: '#526273', fontSize: 14, lineHeight: 20 }, apiNote: { color: '#758494', fontSize: 11, marginTop: 24 } });
