import { useCallback, useState } from 'react';
import { Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import * as Haptics from 'expo-haptics';
import { router } from 'expo-router';
import { api, demoClaimId } from '@/lib/api';
import { useRole } from '@/context/role-context';
import type { Role } from '@/lib/types';
import { AppIcon, ScreenContainer } from '@/components/brand-and-shell';
import { ActionButton } from '@/components/ui';
const roles: { value: Role; label: string; description: string }[] = [{ value: 'FIELD_ADJUSTER', label: 'Field Adjuster', description: 'Assigned claims, inspection tasks, field notes, and analysis.' }, { value: 'POLICYHOLDER', label: 'Policyholder', description: 'Plain-language milestones and requested actions only.' }];
export default function SettingsScreen() { const { role, setRole } = useRole(); const queryClient = useQueryClient(); const [isChanging, setIsChanging] = useState(false); const resetDemo = useMutation({ mutationFn: api.resetDemo, onSuccess: async (payload) => { await queryClient.invalidateQueries({ queryKey: ['claims'] }); await queryClient.invalidateQueries({ queryKey: ['dashboard'] }); await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); const id = demoClaimId(payload); if (id) Alert.alert('Demo claim reset', `Kitchen Water Damage (${id}) is ready.`, [{ text: 'Open claim', onPress: () => router.push({ pathname: '/claim/[id]', params: { id } }) }, { text: 'Stay here', style: 'cancel' }]); else Alert.alert('Demo claim reset', 'The API reset the demo claim. Open Claims to view it.'); }, onError: (error) => Alert.alert('Demo reset failed', error instanceof Error ? error.message : 'The demo claim could not be recreated.') }); const chooseRole = useCallback(async (nextRole: Role) => { if (nextRole === role) return; setIsChanging(true); try { await setRole(nextRole); await Haptics.selectionAsync(); } finally { setIsChanging(false); } }, [role, setRole]); return <ScreenContainer title="Settings" subtitle="Demo controls and application status"><View style={styles.content}><View style={styles.notice}><AppIcon icon="info" size={21} color="#0B7178" /><Text style={styles.noticeText}>Production identity is not implemented. This local switcher is for the AEGIS demonstration only; it does not provide authentication or server-enforced permissions.</Text></View><Text style={styles.heading}>Demo role</Text>{roles.map((option) => <TouchableOpacity key={option.value} accessibilityRole="radio" accessibilityState={{ selected: role === option.value, disabled: isChanging }} onPress={() => void chooseRole(option.value)} disabled={isChanging} style={[styles.roleOption, role === option.value ? styles.roleOptionSelected : null]}><View style={styles.roleIcon}><AppIcon icon={option.value === 'FIELD_ADJUSTER' ? 'assignment' : 'person'} size={21} color={role === option.value ? '#18C3CC' : '#526273'} /></View><View style={styles.roleCopy}><Text style={styles.roleTitle}>{option.label}</Text><Text style={styles.roleDescription}>{option.description}</Text></View>{role === option.value ? <AppIcon icon="check" color="#147D3F" size={21} /> : null}</TouchableOpacity>)}<Text style={styles.heading}>Demo data</Text><View style={styles.resetCard}><Text style={styles.resetTitle}>Kitchen Water Damage</Text><Text style={styles.resetCopy}>Recreate the complete demo claim through POST /api/demo/reset. Existing demo claim state is replaced by the API.</Text><ActionButton label="Reset demo claim" icon="restart" onPress={() => resetDemo.mutate()} loading={resetDemo.isPending} tone="secondary" style={styles.resetButton} /></View></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { flex: 1, padding: 18 }, notice: { backgroundColor: '#E8F8F9', borderColor: '#8BDDE2', borderWidth: 1, borderRadius: 14, padding: 14, flexDirection: 'row', gap: 10 }, noticeText: { color: '#164E63', flex: 1, fontSize: 13, lineHeight: 19 }, heading: { color: '#10233D', fontSize: 17, fontWeight: '800', marginTop: 22, marginBottom: 10 }, roleOption: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderWidth: 1, borderColor: '#DCE3E8', backgroundColor: '#FFFFFF', borderRadius: 14, marginBottom: 9 }, roleOptionSelected: { borderColor: '#18C3CC', borderWidth: 2, backgroundColor: '#F5FEFE' }, roleIcon: { width: 37, height: 37, borderRadius: 10, backgroundColor: '#EEF3F6', alignItems: 'center', justifyContent: 'center' }, roleCopy: { flex: 1 }, roleTitle: { color: '#10233D', fontSize: 15, fontWeight: '800' }, roleDescription: { color: '#526273', fontSize: 12, lineHeight: 17, marginTop: 3 }, resetCard: { backgroundColor: '#FFFFFF', borderColor: '#DCE3E8', borderWidth: 1, borderRadius: 14, padding: 15 }, resetTitle: { color: '#10233D', fontSize: 16, fontWeight: '800' }, resetCopy: { color: '#526273', fontSize: 13, lineHeight: 19, marginTop: 6 }, resetButton: { marginTop: 14 } });
