import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View, type ViewStyle } from 'react-native';
import type { Claim } from '@/lib/types';
import { claimId, claimValue, nestedValue, statusLabel } from '@/lib/types';
import { AppIcon } from './brand-and-shell';
import type { IconName } from '@/lib/icons';

type Tone = 'primary' | 'secondary' | 'danger';
export function ActionButton({ label, onPress, icon, tone = 'primary', loading = false, disabled = false, style }: { label: string; onPress: () => void; icon?: IconName; tone?: Tone; loading?: boolean; disabled?: boolean; style?: ViewStyle }) {
  const secondary = tone === 'secondary';
  return <TouchableOpacity accessibilityRole="button" accessibilityState={{ disabled: disabled || loading }} disabled={disabled || loading} onPress={onPress} style={[styles.button, secondary ? styles.secondary : tone === 'danger' ? styles.danger : styles.primary, disabled || loading ? styles.disabled : null, style]}>{loading ? <ActivityIndicator color={secondary ? '#10233D' : '#FFFFFF'} size="small" /> : icon ? <AppIcon icon={icon} color={secondary ? '#10233D' : '#FFFFFF'} size={18} /> : null}<Text style={[styles.buttonText, secondary ? styles.secondaryText : styles.primaryText]}>{label}</Text></TouchableOpacity>;
}
export function StatusBadge({ status }: { status: unknown }) { const normalized = typeof status === 'string' ? status : 'SUBMITTED'; return <View style={[styles.badge, statusColorMap[normalized] ?? statusColorMap.SUBMITTED]}><Text style={styles.badgeLabel}>{statusLabel(status)}</Text></View>; }
const statusColorMap: Record<string, { backgroundColor: string }> = { SUBMITTED: { backgroundColor: '#DCE3E8' }, IN_REVIEW: { backgroundColor: '#BEEEF1' }, APPROVED: { backgroundColor: '#CDEFD7' }, PAYMENT_SCHEDULED: { backgroundColor: '#FFE2C7' }, PAID: { backgroundColor: '#D8E7FF' }, CLOSED: { backgroundColor: '#E6E3EA' } };
export function MetricCard({ label, value, helper }: { label: string; value: string; helper?: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text>{helper ? <Text style={styles.metricHelper}>{helper}</Text> : null}</View>; }
export function ClaimCard({ claim, onPress }: { claim: Claim; onPress: () => void }) { const insured = nestedValue(claim.insured, ['name'], claimValue(claim, ['insured_name', 'homeowner_name'], 'Policyholder not listed')); const address = claimValue(claim, ['property_address', 'loss_address', 'address']); return <TouchableOpacity accessibilityRole="button" accessibilityLabel={`Open ${claimId(claim)}`} onPress={onPress} style={styles.claimCard}><View style={styles.claimTop}><Text style={styles.claimId}>{claimId(claim)}</Text><StatusBadge status={claim.status} /></View><Text style={styles.insured}>{insured}</Text><Text numberOfLines={1} style={styles.address}>{address}</Text><View style={styles.claimFooter}><Text style={styles.nextAction}>Open claim workspace</Text><AppIcon icon="chevronRight" size={20} color="#10233D" /></View></TouchableOpacity>; }
const styles = StyleSheet.create({
  button: { minHeight: 44, borderRadius: 10, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7 }, primary: { backgroundColor: '#10233D' }, secondary: { backgroundColor: '#E8F8F9', borderWidth: 1, borderColor: '#18C3CC' }, danger: { backgroundColor: '#B54708' }, disabled: { opacity: 0.55 }, buttonText: { fontSize: 14, fontWeight: '800' }, primaryText: { color: '#FFFFFF' }, secondaryText: { color: '#10233D' },
  badge: { alignSelf: 'flex-start', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 20 }, badgeLabel: { color: '#10233D', fontWeight: '800', fontSize: 11, letterSpacing: 0.3 },
  metric: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 15, borderWidth: 1, borderColor: '#DCE3E8', minWidth: 145, flexGrow: 1 }, metricLabel: { color: '#526273', fontSize: 12, fontWeight: '700' }, metricValue: { color: '#10233D', fontSize: 26, fontWeight: '800', marginTop: 6 }, metricHelper: { color: '#0B7178', fontSize: 11, marginTop: 5 },
  claimCard: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DCE3E8', borderRadius: 14, padding: 15, marginBottom: 11 }, claimTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, alignItems: 'center' }, claimId: { color: '#10233D', fontSize: 12, fontWeight: '800', letterSpacing: 0.5 }, insured: { color: '#10233D', fontSize: 17, fontWeight: '800', marginTop: 12 }, address: { color: '#526273', fontSize: 13, marginTop: 4 }, claimFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 14 }, nextAction: { color: '#0B7178', fontSize: 13, fontWeight: '700' },
});
